version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: menshen_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6383:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use dev dockerfile for easier testing
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_test_files:/app/staticfiles
      - media_test_files:/app/media
    ports:
      - "8003:8000"  # Direct access for testing
    environment:
      - DJANGO_SETTINGS_MODULE=menshen.settings.production_test
      - DEBUG=False
      - SECRET_KEY=django-insecure-test-key-for-production-testing-only
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,10.0.0.71
      - DATABASE_NAME=menshen_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A menshen worker -l info
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=menshen.settings.production_test
      - DEBUG=False
      - SECRET_KEY=django-insecure-test-key-for-production-testing-only
      - DATABASE_NAME=menshen_db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"     # HTTP access
      - "8080:80"   # Alternative HTTP port
    volumes:
      - ./config/nginx/nginx-simple.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/sites-available/menshun-simple.conf:/etc/nginx/conf.d/default.conf:ro
      - static_test_files:/var/www/menshun/static:ro
      - media_test_files:/var/www/menshun/media:ro
    depends_on:
      - web

volumes:
  postgres_test_data:
  static_test_files:
  media_test_files: