# Generated by Django 5.2.4 on 2025-07-21 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('USER', 'User Management'), ('VAULT', 'Vault Entry'), ('CRED_TYPE', 'Credential Type'), ('PERMISSION', 'Permission'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], max_length=20)),
                ('action', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('TOKEN_REFRESH', 'Token Refresh'), ('SESSION_EXPIRED', 'Session Expired'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DELETE', 'User Deleted'), ('USER_ACTIVATE', 'User Activated'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_GROUP_ADD', 'User Added to Group'), ('USER_GROUP_REMOVE', 'User Removed from Group'), ('PASSWORD_CHANGE', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('VAULT_CREATE', 'Vault Entry Created'), ('VAULT_VIEW', 'Vault Entry Viewed'), ('VAULT_UPDATE', 'Vault Entry Updated'), ('VAULT_DELETE', 'Vault Entry Deleted'), ('VAULT_RESTORE', 'Vault Entry Restored'), ('VAULT_PASSWORD_VIEW', 'Vault Entry Password Viewed'), ('VAULT_EXPORT', 'Vault Entry Exported'), ('CRED_TYPE_CREATE', 'Credential Type Created'), ('CRED_TYPE_UPDATE', 'Credential Type Updated'), ('CRED_TYPE_DELETE', 'Credential Type Deleted'), ('PERMISSION_GRANT', 'Permission Granted'), ('PERMISSION_REVOKE', 'Permission Revoked'), ('GROUP_CREATE', 'Group Created'), ('GROUP_UPDATE', 'Group Updated'), ('GROUP_DELETE', 'Group Deleted'), ('SYSTEM_CONFIG', 'System Configuration Changed'), ('BACKUP_CREATE', 'Backup Created'), ('BACKUP_RESTORE', 'Backup Restored'), ('FAILED_ACCESS', 'Failed Access Attempt'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity Detected'), ('SECURITY_VIOLATION', 'Security Policy Violation'), ('API_KEY_CREATE', 'API Key Created'), ('API_KEY_REVOKE', 'API Key Revoked')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.BooleanField(default=True)),
                ('risk_score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_systemauditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'action'], name='vault_syste_categor_691a5c_idx'), models.Index(fields=['user', 'timestamp'], name='vault_syste_user_id_e11ebb_idx'), models.Index(fields=['ip_address'], name='vault_syste_ip_addr_320a67_idx'), models.Index(fields=['resource_type', 'resource_id'], name='vault_syste_resourc_890bd7_idx'), models.Index(fields=['success'], name='vault_syste_success_8151f1_idx'), models.Index(fields=['severity'], name='vault_syste_severit_0bbad3_idx')],
            },
        ),
    ]
