# Generated by Django 5.2.4 on 2025-07-21 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_add_system_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntraRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_role_id', models.CharField(max_length=255, unique=True)),
                ('role_template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_built_in', models.BooleanField(default=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vault_entrarole',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='EntraServicePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_app_id', models.CharField(max_length=255, unique=True)),
                ('entra_object_id', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('app_display_name', models.CharField(max_length=255)),
                ('application_type', models.CharField(choices=[('WEB', 'Web Application'), ('SPA', 'Single Page Application'), ('NATIVE', 'Native Application'), ('API', 'API Application')], max_length=20)),
                ('home_page_url', models.URLField(blank=True, null=True)),
                ('sign_in_audience', models.CharField(blank=True, max_length=100, null=True)),
                ('service_principal_type', models.CharField(blank=True, max_length=50, null=True)),
                ('app_roles', models.JSONField(default=list)),
                ('api_permissions', models.JSONField(default=list)),
                ('delegated_permissions', models.JSONField(default=list)),
                ('is_managed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_principals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_entraserviceprincipal',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='EntraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_user_id', models.CharField(max_length=255, unique=True)),
                ('user_principal_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('account_enabled', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled'), ('DELETED', 'Deleted'), ('UNKNOWN', 'Unknown')], default='ACTIVE', max_length=20)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('sync_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('local_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entra_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_entrauser',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('integration_type', models.CharField(choices=[('ENTRA', 'Microsoft Entra ID'), ('PROXMOX', 'Proxmox VE'), ('AWS', 'Amazon Web Services'), ('AZURE', 'Microsoft Azure'), ('GOOGLE', 'Google Cloud Platform')], max_length=20)),
                ('is_enabled', models.BooleanField(default=False)),
                ('configuration', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_integrationconfig',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(choices=[('USER_SYNC', 'User Synchronization'), ('ROLE_SYNC', 'Role Synchronization'), ('USER_CREATE', 'User Creation'), ('ROLE_ASSIGN', 'Role Assignment'), ('ROLE_REMOVE', 'Role Removal'), ('ACCOUNT_DISABLE', 'Account Disable'), ('ACCOUNT_ENABLE', 'Account Enable'), ('SP_CREATE', 'Service Principal Creation'), ('API_PERMISSION', 'API Permission Assignment')], max_length=20)),
                ('integration_type', models.CharField(choices=[('ENTRA', 'Microsoft Entra ID'), ('PROXMOX', 'Proxmox VE'), ('AWS', 'Amazon Web Services'), ('AZURE', 'Microsoft Azure'), ('GOOGLE', 'Google Cloud Platform')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('target_resource', models.CharField(blank=True, max_length=255, null=True)),
                ('task_parameters', models.JSONField(default=dict)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_integrationtask',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntraRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('ELIGIBLE', 'Eligible (PIM)'), ('ACTIVE', 'Active (PIM)')], max_length=20)),
                ('assignment_reason', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('pim_request_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entra_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='vault.entrarole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='vault.entrauser')),
            ],
            options={
                'db_table': 'vault_entraroleassignment',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'role', 'assignment_type')},
            },
        ),
    ]
