# Generated by Django 5.2.4 on 2025-07-23 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_serviceaccount_serviceprincipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprincipal',
            name='owner_entra_id',
            field=models.CharField(blank=True, help_text='Entra user ID of the owner', max_length=255, null=True),
        ),
    ]
