# Generated by Django 5.2.4 on 2025-07-23 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0006_serviceprincipal_owner_entra_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentinelIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_id', models.CharField(help_text='Log Analytics Workspace ID', max_length=255)),
                ('data_collection_endpoint', models.URLField(help_text='Data Collection Endpoint URL')),
                ('data_collection_rule_id', models.CharField(help_text='Data Collection Rule ID', max_length=255)),
                ('stream_name', models.CharField(default='Custom-MenshunPAM_CL', max_length=255)),
                ('tenant_id', models.CharField(help_text='Azure Tenant ID', max_length=255)),
                ('connector_type', models.CharField(choices=[('LOG_ANALYTICS', 'Log Analytics Workspace'), ('EVENT_HUB', 'Azure Event Hub'), ('SYSLOG', 'Syslog Integration')], default='LOG_ANALYTICS', max_length=20)),
                ('batch_size', models.PositiveIntegerField(default=100, help_text='Events per batch')),
                ('batch_timeout', models.PositiveIntegerField(default=60, help_text='Batch timeout in seconds')),
                ('retry_attempts', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('CONFIGURING', 'Configuring')], default='INACTIVE', max_length=20)),
                ('last_successful_send', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('events_sent_today', models.PositiveIntegerField(default=0)),
                ('total_events_sent', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=False)),
                ('send_auth_events', models.BooleanField(default=True)),
                ('send_vault_events', models.BooleanField(default=True)),
                ('send_service_identity_events', models.BooleanField(default=True)),
                ('send_privileged_access_events', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sentinel_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sentinel_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sentinel Integration',
                'verbose_name_plural': 'Sentinel Integrations',
                'db_table': 'vault_sentinelintegration',
            },
        ),
        migrations.CreateModel(
            name='SentinelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('AUTHENTICATION', 'Authentication'), ('VAULT_ACCESS', 'Vault Access'), ('SERVICE_IDENTITY', 'Service Identity'), ('PRIVILEGED_ACCESS', 'Privileged Access'), ('SYSTEM', 'System'), ('SECURITY', 'Security')], max_length=20)),
                ('event_subtype', models.CharField(blank=True, max_length=50)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('event_data', models.JSONField(help_text='Complete event data in JSON format')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('RETRY', 'Retry')], default='PENDING', max_length=10)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vault_sentinelevent',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='vault_senti_event_t_54a901_idx'), models.Index(fields=['status', 'created_at'], name='vault_senti_status_8cf2a8_idx'), models.Index(fields=['user', 'event_type'], name='vault_senti_user_id_b79fe8_idx')],
            },
        ),
    ]
