# Generated by Django 5.2.4 on 2026-07-17 22:10

import vault.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_lowercase_usernames'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', vault.models.CustomUserManager()),
            ],
        ),
    ]
